// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLySinhVien.Data;

#nullable disable

namespace QuanLySinhVien.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230530042411_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("QuanLySinhVien.Data.Khoa", b =>
                {
                    b.Property<int>("MaKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("NameKhoa")
                        .HasColumnType("int");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoa", (string)null);
                });

            modelBuilder.Entity("QuanLySinhVien.Data.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<int>("MaKhoa")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenSV")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaSV");

                    b.HasIndex("MaKhoa");

                    b.ToTable("SinhVien", (string)null);
                });

            modelBuilder.Entity("QuanLySinhVien.Data.SinhVien", b =>
                {
                    b.HasOne("QuanLySinhVien.Data.Khoa", "Khoa")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("QuanLySinhVien.Data.Khoa", b =>
                {
                    b.Navigation("SinhViens");
                });
#pragma warning restore 612, 618
        }
    }
}
